import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import { useState } from 'react'
import { api } from '../lib/api'

type Company = { id: number; name: string; email: string; coinBalance: number; isFrozen: boolean; userCount: number; branchCount: number; createdAt: string }
type Package = { id: number; name: string; moneyAmount: number; coinAmount: number; isActive: boolean; sortOrder: number }
type Setting = { id: number; key: string; value: string; dataType: string; description?: string }
type CoinLedger = { id: number; companyId: number; companyName: string; coinIn: number; coinOut: number; balanceAfter: number; note?: string; createdAt: string }
const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' })
const num = new Intl.NumberFormat('id-ID')

export function AdminPage() {
  const qc = useQueryClient()
  const [pkg, setPkg] = useState<Partial<Package>>({ name: '', moneyAmount: 0, coinAmount: 0, isActive: true, sortOrder: 0 })
  const [setting, setSetting] = useState<Partial<Setting>>({ key: '', value: '', dataType: 'string', description: '' })
  const [adjustment, setAdjustment] = useState({ companyId: 0, amount: 0, note: '' })
  const companies = useQuery({ queryKey: ['admin-companies'], queryFn: async () => (await api.get<Company[]>('/admin/companies')).data })
  const packages = useQuery({ queryKey: ['admin-packages'], queryFn: async () => (await api.get<Package[]>('/admin/topup-packages')).data })
  const settings = useQuery({ queryKey: ['admin-settings'], queryFn: async () => (await api.get<Setting[]>('/admin/platform-settings')).data })
  const ledgers = useQuery({ queryKey: ['admin-ledgers'], queryFn: async () => (await api.get<CoinLedger[]>('/admin/coin-ledgers')).data })
  const freeze = useMutation({ mutationFn: async ({ id, frozen }: { id: number; frozen: boolean }) => api.put(`/admin/companies/${id}/${frozen ? 'freeze' : 'unfreeze'}`), onSuccess: () => qc.invalidateQueries({ queryKey: ['admin-companies'] }) })
  const savePackage = useMutation({ mutationFn: async () => pkg.id ? api.put(`/admin/topup-packages/${pkg.id}`, pkg) : api.post('/admin/topup-packages', pkg), onSuccess: () => { setPkg({ name: '', moneyAmount: 0, coinAmount: 0, isActive: true, sortOrder: 0 }); qc.invalidateQueries({ queryKey: ['admin-packages'] }) } })
  const saveSetting = useMutation({ mutationFn: async () => setting.id ? api.put(`/admin/platform-settings/${setting.id}`, { value: setting.value, dataType: setting.dataType, description: setting.description }) : api.post('/admin/platform-settings', setting), onSuccess: () => { setSetting({ key: '', value: '', dataType: 'string', description: '' }); qc.invalidateQueries({ queryKey: ['admin-settings'] }) } })
  const coinAdjustment = useMutation({ mutationFn: async () => api.post('/admin/coin-adjustments', adjustment), onSuccess: () => { setAdjustment({ companyId: 0, amount: 0, note: '' }); qc.invalidateQueries({ queryKey: ['admin-ledgers'] }); qc.invalidateQueries({ queryKey: ['admin-companies'] }) } })

  return <div className="space-y-6"><div><h2 className="text-3xl font-bold">Super Admin</h2><p className="text-slate-500">Company freeze, package topup, platform setting, coin adjustment.</p></div>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><h3 className="p-5 text-xl font-bold">Companies</h3><Table headers={['Company', 'Coin', 'Users', 'Branches', 'Status', 'Aksi']}>{companies.data?.map((c) => <tr key={c.id}><td className="px-5 py-3"><p className="font-semibold">{c.name}</p><p className="text-slate-500">{c.email}</p></td><td className="px-5 py-3 text-right">{num.format(c.coinBalance)}</td><td className="px-5 py-3 text-right">{c.userCount}</td><td className="px-5 py-3 text-right">{c.branchCount}</td><td className="px-5 py-3">{c.isFrozen ? 'Frozen' : 'Active'}</td><td className="px-5 py-3"><button className="rounded-lg border px-3 py-1 text-xs font-semibold" onClick={() => freeze.mutate({ id: c.id, frozen: !c.isFrozen })}>{c.isFrozen ? 'Unfreeze' : 'Freeze'}</button></td></tr>)}</Table></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-bold">Topup package</h3><div className="mt-4 grid gap-3 md:grid-cols-5"><Input label="Name" value={pkg.name ?? ''} onChange={(v) => setPkg({ ...pkg, name: v })} /><Input label="Money" type="number" value={String(pkg.moneyAmount ?? 0)} onChange={(v) => setPkg({ ...pkg, moneyAmount: Number(v) })} /><Input label="Coin" type="number" value={String(pkg.coinAmount ?? 0)} onChange={(v) => setPkg({ ...pkg, coinAmount: Number(v) })} /><Input label="Sort" type="number" value={String(pkg.sortOrder ?? 0)} onChange={(v) => setPkg({ ...pkg, sortOrder: Number(v) })} /><label className="mt-7 flex gap-2"><input type="checkbox" checked={pkg.isActive ?? true} onChange={(e) => setPkg({ ...pkg, isActive: e.target.checked })} />Active</label></div><button className="mt-4 rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white" onClick={() => savePackage.mutate()}>Save package</button><Table headers={['Name', 'Money', 'Coin', 'Status', 'Aksi']}>{packages.data?.map((p) => <tr key={p.id}><td className="px-5 py-3">{p.name}</td><td className="px-5 py-3 text-right">{money.format(p.moneyAmount)}</td><td className="px-5 py-3 text-right">{num.format(p.coinAmount)}</td><td className="px-5 py-3">{p.isActive ? 'Active' : 'Off'}</td><td className="px-5 py-3"><button className="rounded-lg border px-3 py-1 text-xs" onClick={() => setPkg(p)}>Edit</button></td></tr>)}</Table></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-bold">Platform settings</h3><div className="mt-4 grid gap-3 md:grid-cols-4"><Input label="Key" value={setting.key ?? ''} onChange={(v) => setSetting({ ...setting, key: v })} /><Input label="Value" value={setting.value ?? ''} onChange={(v) => setSetting({ ...setting, value: v })} /><Input label="Data type" value={setting.dataType ?? 'string'} onChange={(v) => setSetting({ ...setting, dataType: v })} /><Input label="Description" value={setting.description ?? ''} onChange={(v) => setSetting({ ...setting, description: v })} /></div><button className="mt-4 rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white" onClick={() => saveSetting.mutate()}>Save setting</button><Table headers={['Key', 'Value', 'Type', 'Aksi']}>{settings.data?.map((s) => <tr key={s.id}><td className="px-5 py-3">{s.key}</td><td className="px-5 py-3">{s.value}</td><td className="px-5 py-3">{s.dataType}</td><td className="px-5 py-3"><button className="rounded-lg border px-3 py-1 text-xs" onClick={() => setSetting(s)}>Edit</button></td></tr>)}</Table></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-bold">Coin adjustment</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><Select label="Company" value={adjustment.companyId} onChange={(v) => setAdjustment({ ...adjustment, companyId: Number(v) })} options={[{ value: 0, label: 'Pilih company' }, ...(companies.data ?? []).map((c) => ({ value: c.id, label: c.name }))]} /><Input label="Amount (+/-)" type="number" value={String(adjustment.amount)} onChange={(v) => setAdjustment({ ...adjustment, amount: Number(v) })} /><Input label="Note" value={adjustment.note} onChange={(v) => setAdjustment({ ...adjustment, note: v })} /></div><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white" onClick={() => coinAdjustment.mutate()}>Adjust coin</button><Table headers={['Company', 'In', 'Out', 'Balance', 'Note']}>{ledgers.data?.slice(0, 20).map((l) => <tr key={l.id}><td className="px-5 py-3">{l.companyName}</td><td className="px-5 py-3 text-right">{num.format(l.coinIn)}</td><td className="px-5 py-3 text-right">{num.format(l.coinOut)}</td><td className="px-5 py-3 text-right">{num.format(l.balanceAfter)}</td><td className="px-5 py-3">{l.note}</td></tr>)}</Table></section>
  </div>
}
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="overflow-x-auto"><table className="mt-4 min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50"><tr>{headers.map((h) => <th key={h} className="px-5 py-3 text-left">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; type?: string; onChange: (v: string) => void }) { return <label className="block"><span className="text-sm font-medium text-slate-700">{label}</span><input type={type} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" value={value} onChange={(e) => onChange(e.target.value)} /></label> }
function Select({ label, value, onChange, options }: { label: string; value: string | number; onChange: (v: string | number) => void; options: { value: string | number; label: string }[] }) { return <label className="block"><span className="text-sm font-medium text-slate-700">{label}</span><select className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" value={value} onChange={(e) => onChange(Number.isNaN(Number(e.target.value)) ? e.target.value : Number(e.target.value))}>{options.map((o) => <option key={String(o.value)} value={o.value}>{o.label}</option>)}</select></label> }
